modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="create_dragon_lib"
version="${file.jarVersion}"
displayName="Create: Dragon Lib"
authors="LimonBlaze & MarbleGateKeeper"
description='''
A library for Create addons.
'''

[[dependencies.create_dragon_lib]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.create_dragon_lib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1)"
    ordering="NONE"
    side="BOTH"
[[dependencies.create_dragon_lib]]
    modId="create"
    mandatory=true
    versionRange="[0.5.1.d,)"
    ordering="NONE"
    side="BOTH"
