@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package plus.dragons.createdragonlib.advancement;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;