@ParametersAreNonnullByDefault
@MethodsReturnNonnullByDefault
package plus.dragons.createdragonlib.advancement.critereon;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;