name: Publish to Maven
on: [workflow_dispatch]

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Make Gradle Wrapper Executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew

      - name: Publish to Maven
        run: ./gradlew publish -PrepositoryUsername=${{ secrets.MAVEN_USERNAME }} -PrepositoryPassword=${{ secrets.MAVEN_PASSWORD }}
